#!/bin/sh
# preinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    install|upgrade)
        if [ -L /usr/bin/mintsources ]; then
        	echo "Removing symbolic link /usr/bin/mintsources"
            rm -f /usr/bin/mintsources
        fi
    ;;
esac
